<?php
	add_action( 'init', 'syn_admin_columns' );
	function syn_admin_columns() {
		if ( function_exists( 'ac_register_columns' ) ) {
			ac_register_columns( 'post', [
				[
					'columns' => [
						'title'              => [
							'type'       => 'title',
							'label'      => 'Title',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'title',
						],
						'categories'         => [
							'type'                 => 'categories',
							'label'                => 'Category',
							'width'                => '150',
							'width_unit'           => 'px',
							'edit'                 => 'off',
							'sort'                 => 'on',
							'filter'               => 'on',
							'name'                 => 'categories',
							'enable_term_creation' => 'off',
							'filter_label'         => '',
						],
						'taxonomy-microblog' => [
							'type'                 => 'taxonomy-microblog',
							'label'                => 'Microblog',
							'width'                => '',
							'width_unit'           => '%',
							'edit'                 => 'off',
							'sort'                 => 'on',
							'filter'               => 'on',
							'filter_label'         => 'Microblog',
							'name'                 => 'taxonomy-microblog',
							'enable_term_creation' => 'off',
						],
						'author'             => [
							'type'       => 'author',
							'label'      => 'Author/Owner',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'author',
						],
						'5ac1849f2afa2'      => [
							'type'          => 'column-date_published',
							'label'         => 'Published',
							'width'         => '120',
							'width_unit'    => 'px',
							'date_format'   => 'diff',
							'edit'          => 'off',
							'sort'          => 'on',
							'filter'        => 'off',
							'filter_label'  => '',
							'filter_format' => '',
							'name'          => '5ac1849f2afa2',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627258ef',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'page', [
				[
					'columns' => [
						'title'         => [
							'type'       => 'title',
							'label'      => 'Title',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'title',
						],
						'5abeb1739663d' => [
							'type'         => 'column-page_template',
							'label'        => 'Page Template',
							'width'        => '',
							'width_unit'   => '%',
							'edit'         => 'off',
							'sort'         => 'on',
							'filter'       => 'on',
							'filter_label' => '',
							'name'         => '5abeb1739663d',
						],
						'author'        => [
							'type'       => 'author',
							'label'      => 'Author/Owner',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'author',
						],
						'5abeb1739a2c7' => [
							'type'         => 'column-acf_field',
							'label'        => 'Co',
							'width'        => '25',
							'width_unit'   => 'px',
							'field'        => 'field_59ab362921325',
							'edit'         => 'off',
							'sort'         => 'off',
							'filter'       => 'on',
							'filter_label' => 'Contact',
							'name'         => '5abeb1739a2c7',
						],
						'5abeb1739d954' => [
							'type'         => 'column-acf_field',
							'label'        => 'Ro',
							'width'        => '25',
							'width_unit'   => 'px',
							'field'        => 'field_59ab36d12132b',
							'edit'         => 'off',
							'sort'         => 'off',
							'filter'       => 'on',
							'filter_label' => 'Roster',
							'name'         => '5abeb1739d954',
						],
						'5abeb1739e916' => [
							'type'         => 'column-acf_field',
							'label'        => 'Ca',
							'width'        => '25',
							'width_unit'   => 'px',
							'field'        => 'field_59b720b6e759d',
							'edit'         => 'off',
							'sort'         => 'off',
							'filter'       => 'on',
							'filter_label' => 'Calendar',
							'name'         => '5abeb1739e916',
						],
						'5abeb21116016' => [
							'type'         => 'column-acf_field',
							'label'        => 'Mb',
							'width'        => '25',
							'width_unit'   => 'px',
							'field'        => 'field_59ab366c21327',
							'edit'         => 'off',
							'sort'         => 'off',
							'filter'       => 'on',
							'filter_label' => 'Microblog',
							'name'         => '5abeb21116016',
						],
						'5abeb21116f69' => [
							'type'         => 'column-acf_field',
							'label'        => 'GM',
							'width'        => '25',
							'width_unit'   => 'px',
							'field'        => 'field_5a41c0a82a649',
							'edit'         => 'off',
							'sort'         => 'off',
							'filter'       => 'on',
							'filter_label' => 'Google Map',
							'name'         => '5abeb21116f69',
						],
						'5abeb21117e5b' => [
							'type'         => 'column-acf_field',
							'label'        => 'Vi',
							'width'        => '25',
							'width_unit'   => 'px',
							'field'        => 'field_5a41c16e2a64d',
							'edit'         => 'off',
							'sort'         => 'off',
							'filter'       => 'on',
							'filter_label' => 'Video',
							'name'         => '5abeb21117e5b',
						],
					],
					'layout'  => [
						'id'        => '5ac1f6276cad5',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'tinymcetemplates', [
				[
					'columns' => [
						'5abcb001ba50e' => [
							'type'         => 'column-title_raw',
							'label'        => 'Title',
							'width'        => '',
							'width_unit'   => '%',
							'post_link_to' => 'edit_post',
							'edit'         => 'on',
							'sort'         => 'on',
							'name'         => '5abcb001ba50e',
						],
						'5abcab68da79c' => [
							'type'         => 'column-content',
							'label'        => 'Content',
							'width'        => '75',
							'width_unit'   => '%',
							'string_limit' => '',
							'before'       => '',
							'after'        => '',
							'edit'         => 'on',
							'sort'         => 'off',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => '5abcab68da79c',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627870c5',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'syn_calendar', [
				[
					'columns' => [
						'title'         => [
							'type'       => 'title',
							'label'      => 'Title',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'title',
						],
						'5ac1c5d9c60b2' => [
							'type'            => 'column-acf_field',
							'label'           => 'Google Calendar ID',
							'width'           => '',
							'width_unit'      => '%',
							'field'           => 'field_59b80aa817de3',
							'character_limit' => '100',
							'edit'            => 'off',
							'sort'            => 'on',
							'filter'          => 'off',
							'filter_label'    => '',
							'name'            => '5ac1c5d9c60b2',
						],
						'5ac1c5d9cdfeb' => [
							'type'              => 'column-author_name',
							'label'             => 'Author/Owner',
							'width'             => '',
							'width_unit'        => '%',
							'display_author_as' => 'display_name',
							'user_link_to'      => '',
							'edit'              => 'off',
							'sort'              => 'on',
							'filter'            => 'on',
							'filter_label'      => 'Author/Owner',
							'name'              => '5ac1c5d9cdfeb',
						],
						'5ac1c5d9d14df' => [
							'type'         => 'column-meta',
							'label'        => 'Last Sync',
							'width'        => '150',
							'width_unit'   => 'px',
							'field'        => 'syn_calendar_last_sync',
							'field_type'   => 'date',
							'date_format'  => 'diff',
							'before'       => '',
							'after'        => '',
							'edit'         => 'off',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => '5ac1c5d9d14df',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627925b7',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'syn_event', [
				[
					'columns' => [
						'title'         => [
							'type'       => 'title',
							'label'      => 'Title',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'title',
						],
						'5ac1c6c389087' => [
							'type'          => 'column-acf_field',
							'label'         => 'Start Date',
							'width'         => '150',
							'width_unit'    => 'px',
							'field'         => 'field_590b73c246359',
							'date_format'   => 'F j, Y',
							'edit'          => 'off',
							'sort'          => 'on',
							'filter'        => 'off',
							'filter_label'  => '',
							'filter_format' => '',
							'name'          => '5ac1c6c389087',
						],
						'5ac1c6c38eb37' => [
							'type'          => 'column-acf_field',
							'label'         => 'End Date',
							'width'         => '150',
							'width_unit'    => 'px',
							'field'         => 'field_590b74004635b',
							'date_format'   => 'F j, Y',
							'edit'          => 'off',
							'sort'          => 'on',
							'filter'        => 'off',
							'filter_label'  => '',
							'filter_format' => '',
							'name'          => '5ac1c6c38eb37',
						],
						'5ac1c6c331e6b' => [
							'type'                  => 'column-meta',
							'label'                 => 'Calendar',
							'width'                 => '',
							'width_unit'            => '%',
							'field'                 => 'syn_event_calendar_id',
							'field_type'            => 'title_by_id',
							'post_property_display' => 'title',
							'post_link_to'          => 'edit_post',
							'before'                => '',
							'after'                 => '',
							'edit'                  => 'off',
							'sort'                  => 'on',
							'filter'                => 'on',
							'filter_label'          => 'Calendar',
							'name'                  => '5ac1c6c331e6b',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627a2517',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'wp-media', [
				[
					'columns' => [
						'title'                   => [
							'type'       => 'title',
							'label'      => 'Title & Alt Text',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'on',
							'sort'       => 'on',
							'name'       => 'title',
						],
						'5ac186c82a24c'           => [
							'type'       => 'column-caption',
							'label'      => 'Caption',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'on',
							'sort'       => 'on',
							'name'       => '5ac186c82a24c',
						],
						'5ac189a81eec1'           => [
							'type'         => 'column-description',
							'label'        => 'Description',
							'width'        => '',
							'width_unit'   => '%',
							'string_limit' => '',
							'before'       => '',
							'after'        => '',
							'edit'         => 'on',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => '5ac189a81eec1',
						],
						'taxonomy-media_category' => [
							'type'                 => 'taxonomy-media_category',
							'label'                => 'Categories',
							'width'                => '',
							'width_unit'           => '%',
							'edit'                 => 'on',
							'enable_term_creation' => 'on',
							'sort'                 => 'on',
							'filter'               => 'on',
							'filter_label'         => 'Categories',
							'name'                 => 'taxonomy-media_category',
						],
						'author'                  => [
							'type'         => 'author',
							'label'        => 'Uploaded by',
							'width'        => '',
							'width_unit'   => '%',
							'edit'         => 'off',
							'sort'         => 'on',
							'filter'       => 'on',
							'filter_label' => 'Uploaded by',
							'name'         => 'author',
						],
						'parent'                  => [
							'type'         => 'parent',
							'label'        => 'Attached to',
							'width'        => '',
							'width_unit'   => '%',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => 'parent',
						],
						'5ac187d55f0ce'           => [
							'type'       => 'column-dimensions',
							'label'      => 'Dimensions',
							'width'      => '120',
							'width_unit' => 'px',
							'before'     => '',
							'after'      => '',
							'sort'       => 'on',
							'name'       => '5ac187d55f0ce',
						],
						'5ac18bbf2c850'           => [
							'type'                  => 'column-available_sizes',
							'label'                 => 'Sizes',
							'width'                 => '110',
							'width_unit'            => 'px',
							'include_missing_sizes' => '1',
							'sort'                  => 'off',
							'name'                  => '5ac18bbf2c850',
						],
						'5ac1a2d1370ff'           => [
							'type'         => 'column-mime_type',
							'label'        => 'Mime Type',
							'width'        => '150',
							'width_unit'   => 'px',
							'edit'         => 'off',
							'sort'         => 'on',
							'filter'       => 'on',
							'filter_label' => 'Mime Type',
							'name'         => '5ac1a2d1370ff',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627b1152',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'wp-users', [
				[
					'columns' => [
						'5ac1cadc9a0b4' => [
							'type'         => 'column-first_name',
							'label'        => 'First Name',
							'width'        => '',
							'width_unit'   => 'px',
							'edit'         => 'on',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => '5ac1cadc9a0b4',
						],
						'5ac1cadc9ac48' => [
							'type'         => 'column-last_name',
							'label'        => 'Last Name',
							'width'        => '',
							'width_unit'   => '%',
							'edit'         => 'on',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => '5ac1cadc9ac48',
						],
						'5ac1cbcf304a0' => [
							'type'         => 'column-acf_field',
							'label'        => 'Prefix',
							'width'        => '100',
							'width_unit'   => 'px',
							'field'        => 'field_5a6570eff3d03',
							'edit'         => 'on',
							'sort'         => 'on',
							'filter'       => 'on',
							'filter_label' => 'Prefix',
							'name'         => '5ac1cbcf304a0',
						],
						'5abe434f71334' => [
							'type'            => 'column-acf_field',
							'label'           => 'Title',
							'width'           => '',
							'width_unit'      => '%',
							'field'           => 'field_59c3de9804864',
							'character_limit' => '100',
							'edit'            => 'on',
							'sort'            => 'on',
							'filter'          => 'off',
							'filter_label'    => '',
							'name'            => '5abe434f71334',
						],
						'email'         => [
							'type'         => 'email',
							'label'        => 'Email',
							'width'        => '',
							'width_unit'   => '%',
							'edit'         => 'on',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => '',
							'name'         => 'email',
						],
						'5ac1cadc9e591' => [
							'type'            => 'column-acf_field',
							'label'           => 'Phone',
							'width'           => '150',
							'width_unit'      => 'px',
							'field'           => 'field_59c3de9804c7e',
							'character_limit' => '20',
							'edit'            => 'on',
							'sort'            => 'on',
							'filter'          => 'off',
							'filter_label'    => '',
							'name'            => '5ac1cadc9e591',
						],
						'5ac1cadc9f61e' => [
							'type'            => 'column-acf_field',
							'label'           => 'Ext',
							'width'           => '100',
							'width_unit'      => 'px',
							'field'           => 'field_59c3de9804e7c',
							'character_limit' => '10',
							'edit'            => 'on',
							'sort'            => 'on',
							'filter'          => 'off',
							'filter_label'    => '',
							'name'            => '5ac1cadc9f61e',
						],
						'role'          => [
							'type'         => 'role',
							'label'        => 'Role',
							'width'        => '140',
							'width_unit'   => 'px',
							'edit'         => 'on',
							'sort'         => 'on',
							'filter'       => 'on',
							'filter_label' => 'Role',
							'name'         => 'role',
						],
						'5abe434f78214' => [
							'type'         => 'column-acf_field',
							'label'        => 'Teacher?',
							'width'        => '100',
							'width_unit'   => 'px',
							'field'        => 'field_59c3de980525e',
							'edit'         => 'off',
							'sort'         => 'on',
							'filter'       => 'off',
							'filter_label' => 'Teacher?',
							'name'         => '5abe434f78214',
						],
						'5abe465d13297' => [
							'type'                  => 'column-acf_field',
							'label'                 => 'Teacher Page',
							'width'                 => '',
							'width_unit'            => '%',
							'field'                 => 'field_59f7a2d72ed22',
							'post_property_display' => 'title',
							'post_link_to'          => 'edit_post',
							'edit'                  => 'off',
							'sort'                  => 'on',
							'filter'                => 'off',
							'filter_label'          => '',
							'name'                  => '5abe465d13297',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627c7b0f',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'wp-taxonomy_category', [
				[
					'columns' => [
						'name'  => [
							'type'       => 'name',
							'label'      => 'Name',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'name',
						],
						'slug'  => [
							'type'       => 'slug',
							'label'      => 'Slug',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'slug',
						],
						'posts' => [
							'type'       => 'posts',
							'label'      => 'Posts',
							'width'      => '',
							'width_unit' => '%',
							'sort'       => 'on',
							'name'       => 'posts',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627e3b30',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'wp-taxonomy_post_tag', [
				[
					'columns' => [
						'name'  => [
							'type'       => 'name',
							'label'      => 'Name',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'on',
							'sort'       => 'on',
							'name'       => 'name',
						],
						'slug'  => [
							'type'       => 'slug',
							'label'      => 'Slug',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'on',
							'sort'       => 'on',
							'name'       => 'slug',
						],
						'posts' => [
							'type'       => 'posts',
							'label'      => 'Posts',
							'width'      => '',
							'width_unit' => '%',
							'sort'       => 'on',
							'name'       => 'posts',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627ec9d7',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'wp-taxonomy_media_category', [
				[
					'columns' => [
						'name'  => [
							'type'       => 'name',
							'label'      => 'Name',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'on',
							'sort'       => 'on',
							'name'       => 'name',
						],
						'slug'  => [
							'type'       => 'slug',
							'label'      => 'Slug',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'on',
							'sort'       => 'on',
							'name'       => 'slug',
						],
						'posts' => [
							'type'       => 'posts',
							'label'      => 'Posts',
							'width'      => '',
							'width_unit' => '%',
							'sort'       => 'on',
							'name'       => 'posts',
						],
					],
					'layout'  => [
						'id'        => '5ac1f627f3909',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
			ac_register_columns( 'wp-taxonomy_microblog', [
				[
					'columns' => [
						'name'  => [
							'type'       => 'name',
							'label'      => 'Name',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'name',
						],
						'slug'  => [
							'type'       => 'slug',
							'label'      => 'Slug',
							'width'      => '',
							'width_unit' => '%',
							'edit'       => 'off',
							'sort'       => 'on',
							'name'       => 'slug',
						],
						'posts' => [
							'type'       => 'posts',
							'label'      => 'Posts',
							'width'      => '',
							'width_unit' => '%',
							'sort'       => 'on',
							'name'       => 'posts',
						],
					],
					'layout'  => [
						'id'        => '5ac1f6280501c',
						'name'      => 'Imported',
						'roles'     => false,
						'users'     => false,
						'read_only' => false,
					],
				],
			] );
		}
	}